/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clved;

import javax.swing.ImageIcon;

/**
 *
 * @author Tim
 */
public class GUI_Donador extends javax.swing.JFrame {

    Lista listaDonadores = new Lista();
    Donante donador;

        String nombre;
        String apellido;
        int edad;
        String enfermedades = "";
        String tipoSangre;
        String sexo;
        String parentezco;
        
    static String informacionLista = "";
    
    /**
     * Creates new form GUI_Donador
     */
    public GUI_Donador() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        lblTipoSangre = new javax.swing.JLabel();
        lblRinion = new javax.swing.JLabel();
        lblClved = new javax.swing.JLabel();
        btnAgregarDonador = new javax.swing.JButton();
        lblNombres = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblEnfermedades = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        pnlEnfermedades = new javax.swing.JPanel();
        rbtnPresionArterial = new javax.swing.JRadioButton();
        rbtnDiabetes = new javax.swing.JRadioButton();
        rbtnHepatitis = new javax.swing.JRadioButton();
        rbtnEnfermedadCardiaca = new javax.swing.JRadioButton();
        rbtnEnfermedadRenal = new javax.swing.JRadioButton();
        rbtnNinguno = new javax.swing.JRadioButton();
        rbtnVih = new javax.swing.JRadioButton();
        btnContinuar = new javax.swing.JButton();
        cmbGrado3 = new javax.swing.JComboBox<>();
        cmbSexo = new javax.swing.JComboBox<>();
        lblParentezco = new javax.swing.JLabel();
        lblTipoSangrel = new javax.swing.JLabel();
        cmbTipoSangre = new javax.swing.JComboBox<>();
        cmbGrado1 = new javax.swing.JComboBox<>();
        cmbGrado2 = new javax.swing.JComboBox<>();
        txtEdad = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFondo.setBackground(new java.awt.Color(255, 255, 255));
        pnlFondo.setLayout(null);

        lblTipoSangre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tipo-de-sangre.png"))); // NOI18N
        pnlFondo.add(lblTipoSangre);
        lblTipoSangre.setBounds(570, 20, 150, 150);

        lblRinion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RiñonPequeño.png"))); // NOI18N
        pnlFondo.add(lblRinion);
        lblRinion.setBounds(10, 500, 50, 50);

        lblClved.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblClved.setText("CLVED");
        pnlFondo.add(lblClved);
        lblClved.setBounds(70, 510, 70, 34);

        btnAgregarDonador.setBackground(new java.awt.Color(204, 255, 255));
        btnAgregarDonador.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        btnAgregarDonador.setText("AGREGAR DONADOR");
        btnAgregarDonador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDonadorActionPerformed(evt);
            }
        });
        pnlFondo.add(btnAgregarDonador);
        btnAgregarDonador.setBounds(420, 500, 220, 30);

        lblNombres.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblNombres.setText("Nombres");
        pnlFondo.add(lblNombres);
        lblNombres.setBounds(20, 270, 99, 29);

        lblApellidos.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblApellidos.setText("Apellidos");
        pnlFondo.add(lblApellidos);
        lblApellidos.setBounds(20, 310, 102, 29);

        lblEnfermedades.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblEnfermedades.setText("Enfermedades");
        pnlFondo.add(lblEnfermedades);
        lblEnfermedades.setBounds(550, 310, 180, 29);

        lblSexo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblSexo.setText("Sexo");
        pnlFondo.add(lblSexo);
        lblSexo.setBounds(20, 230, 53, 29);

        lblEdad.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblEdad.setText("Edad");
        pnlFondo.add(lblEdad);
        lblEdad.setBounds(20, 350, 55, 29);

        lblTitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblTitulo.setText("POSIBLE DONADOR");
        pnlFondo.add(lblTitulo);
        lblTitulo.setBounds(320, 10, 220, 29);

        lblUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Usuario.png"))); // NOI18N
        pnlFondo.add(lblUsuario);
        lblUsuario.setBounds(80, 30, 160, 150);

        pnlEnfermedades.setBackground(new java.awt.Color(255, 255, 255));
        pnlEnfermedades.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        rbtnPresionArterial.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        rbtnPresionArterial.setText("Presión Arterial Alta");

        rbtnDiabetes.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        rbtnDiabetes.setText("Diabetes");

        rbtnHepatitis.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        rbtnHepatitis.setText("Hepatitis");

        rbtnEnfermedadCardiaca.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        rbtnEnfermedadCardiaca.setText("Enfermedad Cardiaca");
        rbtnEnfermedadCardiaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnEnfermedadCardiacaActionPerformed(evt);
            }
        });

        rbtnEnfermedadRenal.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        rbtnEnfermedadRenal.setText("Enfermedad Renal");

        rbtnNinguno.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        rbtnNinguno.setText("Ninguno");

        rbtnVih.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        rbtnVih.setText("VIH");

        javax.swing.GroupLayout pnlEnfermedadesLayout = new javax.swing.GroupLayout(pnlEnfermedades);
        pnlEnfermedades.setLayout(pnlEnfermedadesLayout);
        pnlEnfermedadesLayout.setHorizontalGroup(
            pnlEnfermedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEnfermedadesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEnfermedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnHepatitis)
                    .addComponent(rbtnDiabetes)
                    .addComponent(rbtnPresionArterial)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEnfermedadesLayout.createSequentialGroup()
                        .addComponent(rbtnVih)
                        .addGap(110, 110, 110)))
                .addGroup(pnlEnfermedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEnfermedadesLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(pnlEnfermedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnEnfermedadRenal)
                            .addComponent(rbtnEnfermedadCardiaca))
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEnfermedadesLayout.createSequentialGroup()
                        .addComponent(rbtnNinguno)
                        .addContainerGap())))
        );
        pnlEnfermedadesLayout.setVerticalGroup(
            pnlEnfermedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEnfermedadesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEnfermedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEnfermedadesLayout.createSequentialGroup()
                        .addComponent(rbtnEnfermedadCardiaca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnEnfermedadRenal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbtnNinguno))
                    .addGroup(pnlEnfermedadesLayout.createSequentialGroup()
                        .addComponent(rbtnPresionArterial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnDiabetes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnHepatitis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnVih)
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnlFondo.add(pnlEnfermedades);
        pnlEnfermedades.setBounds(420, 350, 410, 140);

        btnContinuar.setBackground(new java.awt.Color(204, 255, 204));
        btnContinuar.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        btnContinuar.setText("CONTINUAR");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        pnlFondo.add(btnContinuar);
        btnContinuar.setBounds(680, 520, 150, 30);

        cmbGrado3.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        cmbGrado3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3er Grado", "Bisabuelo/a", "Tio/a", "Sobrino/a", "Bisnieto/a" }));
        cmbGrado3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGrado3ActionPerformed(evt);
            }
        });
        pnlFondo.add(cmbGrado3);
        cmbGrado3.setBounds(704, 270, 142, 30);

        cmbSexo.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Femenino", "Masculino" }));
        cmbSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSexoActionPerformed(evt);
            }
        });
        pnlFondo.add(cmbSexo);
        cmbSexo.setBounds(160, 230, 160, 30);

        lblParentezco.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblParentezco.setText("Parentezco");
        pnlFondo.add(lblParentezco);
        lblParentezco.setBounds(560, 230, 130, 29);

        lblTipoSangrel.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblTipoSangrel.setText("Tipo de Sangre");
        pnlFondo.add(lblTipoSangrel);
        lblTipoSangrel.setBounds(430, 190, 180, 29);

        cmbTipoSangre.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        cmbTipoSangre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "A+", "B+", "O+", "AB+", "A-", "B-", "O-", "AB-" }));
        cmbTipoSangre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoSangreActionPerformed(evt);
            }
        });
        pnlFondo.add(cmbTipoSangre);
        cmbTipoSangre.setBounds(680, 190, 150, 30);

        cmbGrado1.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        cmbGrado1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1er Grado", "Conyugue", "Padre", "Madre", "Suegro/a", "Hijo/a", "Yerno", "Nuera", " ", " " }));
        cmbGrado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGrado1ActionPerformed(evt);
            }
        });
        pnlFondo.add(cmbGrado1);
        cmbGrado1.setBounds(420, 270, 130, 30);

        cmbGrado2.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        cmbGrado2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2do Grado", "Abuelo/a", "Hermano/a", "Cuñado/a", "Nieto/a" }));
        cmbGrado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGrado2ActionPerformed(evt);
            }
        });
        pnlFondo.add(cmbGrado2);
        cmbGrado2.setBounds(560, 270, 130, 30);
        pnlFondo.add(txtEdad);
        txtEdad.setBounds(160, 350, 80, 30);
        pnlFondo.add(txtNombre);
        txtNombre.setBounds(160, 270, 160, 30);
        pnlFondo.add(txtApellido);
        txtApellido.setBounds(160, 310, 160, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarDonadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDonadorActionPerformed
        // TODO add your handling code here:
        
        nombre = txtNombre.getText();
        apellido = txtApellido.getText();
        edad = Integer.parseInt(txtEdad.getText());

        tipoSangre = (String) cmbTipoSangre.getSelectedItem();
        GUI_Receptor.miMatriz.insertar(tipoSangre);
        
        sexo = (String) cmbSexo.getSelectedItem();
        
        parentezco = (String) cmbGrado1.getSelectedItem();
        parentezco = (String) cmbGrado2.getSelectedItem();
        parentezco = (String) cmbGrado3.getSelectedItem();
        
        if (rbtnPresionArterial.isSelected()) {
            enfermedades += rbtnPresionArterial.getText();
        }
        if (rbtnEnfermedadCardiaca.isSelected()) {
            enfermedades += rbtnEnfermedadCardiaca.getText() + " ";
        }
        if (rbtnEnfermedadRenal.isSelected()) {
            enfermedades += rbtnEnfermedadRenal.getText() + " ";
        }
        if (rbtnHepatitis.isSelected()) {
            enfermedades += rbtnHepatitis.getText() + " ";
        }
        if (rbtnVih.isSelected()) {
            enfermedades += rbtnVih.getText() + " ";
        }
        if (rbtnDiabetes.isSelected()) {
            enfermedades += rbtnDiabetes.getText();
        }
        if (rbtnNinguno.isSelected()) {
            enfermedades = "";
            rbtnDiabetes.setSelected(false);
            rbtnEnfermedadCardiaca.setSelected(false);
            rbtnEnfermedadRenal.setSelected(false);
            rbtnPresionArterial.setSelected(false);
            rbtnVih.setSelected(false);
        }
        
        donador = new Donante(nombre, apellido, edad, sexo, tipoSangre, enfermedades, parentezco);

        listaDonadores.insertarNodo(donador);
        
        informacionLista += listaDonadores.imprimirAristas();
        
        limpiar();
        iniacilizar();
        
    }//GEN-LAST:event_btnAgregarDonadorActionPerformed

    private void rbtnEnfermedadCardiacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnEnfermedadCardiacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnEnfermedadCardiacaActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        // TODO add your handling code here:
        
        GUI_DatosReceptor datosReceptor = new GUI_DatosReceptor();
        datosReceptor.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void cmbGrado3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGrado3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGrado3ActionPerformed

    private void cmbSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSexoActionPerformed
        // TODO add your handling code here:
        if( cmbSexo.getSelectedItem().equals("Masculino")){
            lblUsuario.setIcon(new ImageIcon(getClass().getResource("/Imagenes/Hombre.png")));
        }if( cmbSexo.getSelectedItem().equals("Femenino")){
            lblUsuario.setIcon(new ImageIcon(getClass().getResource("/Imagenes/Mujer.png")));
        }if( cmbSexo.getSelectedItem().equals("Selecionar")){
            lblUsuario.setIcon(new ImageIcon(getClass().getResource("/Imagenes/Usuario.png")));
        }
    }//GEN-LAST:event_cmbSexoActionPerformed

    private void cmbTipoSangreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoSangreActionPerformed
        // TODO add your handling code here:
        if( cmbTipoSangre.getSelectedItem().equals("A+")){
            lblTipoSangre.setIcon(new ImageIcon(getClass().getResource("/Imagenes/A+.png")));
        }
        if( cmbTipoSangre.getSelectedItem().equals("A-")){
            lblTipoSangre.setIcon(new ImageIcon(getClass().getResource("/Imagenes/A-.png")));
        }
        if( cmbTipoSangre.getSelectedItem().equals("B+")){
            lblTipoSangre.setIcon(new ImageIcon(getClass().getResource("/Imagenes/B+.png")));
        }
        if( cmbTipoSangre.getSelectedItem().equals("B-")){
            lblTipoSangre.setIcon(new ImageIcon(getClass().getResource("/Imagenes/B-.png")));
        }
        if( cmbTipoSangre.getSelectedItem().equals("O+")){
            lblTipoSangre.setIcon(new ImageIcon(getClass().getResource("/Imagenes/O+.png")));
        }
        if( cmbTipoSangre.getSelectedItem().equals("AB+")){
            lblTipoSangre.setIcon(new ImageIcon(getClass().getResource("/Imagenes/AB+.png")));
        }
        if( cmbTipoSangre.getSelectedItem().equals("AB-")){
            lblTipoSangre.setIcon(new ImageIcon(getClass().getResource("/Imagenes/AB-.png")));
        }
        if( cmbTipoSangre.getSelectedItem().equals("O-")){
            lblTipoSangre.setIcon(new ImageIcon(getClass().getResource("/Imagenes/O-.png")));
        }
    }//GEN-LAST:event_cmbTipoSangreActionPerformed

    private void cmbGrado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGrado1ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_cmbGrado1ActionPerformed

    private void cmbGrado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGrado2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGrado2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Donador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Donador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Donador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Donador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Donador().setVisible(true);
            }
        });
    }
    
    public void limpiar(){
        txtApellido.setText("");
        txtEdad.setText("");
        txtNombre.setText("");
        
        cmbSexo.setSelectedIndex(0);
        cmbTipoSangre.setSelectedIndex(0);
        
        cmbGrado1.setSelectedIndex(0);
        cmbGrado2.setSelectedIndex(0);
        cmbGrado3.setSelectedIndex(0);
        
        rbtnDiabetes.setSelected(false);
        rbtnEnfermedadCardiaca.setSelected(false);
        rbtnEnfermedadRenal.setSelected(false);
        rbtnHepatitis.setSelected(false);
        rbtnNinguno.setSelected(false);
        rbtnPresionArterial.setSelected(false);
        rbtnVih.setSelected(false);

    }
     public void iniacilizar(){
         nombre = "";
         apellido = "";
         edad = 0;
         parentezco = "";
         sexo = "";
         tipoSangre = "";
         enfermedades = "";
         
         
         
         
     }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarDonador;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JComboBox<String> cmbGrado1;
    private javax.swing.JComboBox<String> cmbGrado2;
    private javax.swing.JComboBox<String> cmbGrado3;
    private javax.swing.JComboBox<String> cmbSexo;
    private javax.swing.JComboBox<String> cmbTipoSangre;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblClved;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblEnfermedades;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblParentezco;
    private javax.swing.JLabel lblRinion;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTipoSangre;
    private javax.swing.JLabel lblTipoSangrel;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlEnfermedades;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JRadioButton rbtnDiabetes;
    private javax.swing.JRadioButton rbtnEnfermedadCardiaca;
    private javax.swing.JRadioButton rbtnEnfermedadRenal;
    private javax.swing.JRadioButton rbtnHepatitis;
    private javax.swing.JRadioButton rbtnNinguno;
    private javax.swing.JRadioButton rbtnPresionArterial;
    private javax.swing.JRadioButton rbtnVih;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
