/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clved;

import javax.swing.ImageIcon;

/**
 *
 * @author Tim
 */
public class GUI_Menu extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Menu
     */
    public GUI_Menu() {
        initComponents();
        setLocationRelativeTo(null);
       this.setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Riñon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        lblDoctor = new javax.swing.JLabel();
        lblRinion = new javax.swing.JLabel();
        lblClved = new javax.swing.JLabel();
        btnDescubiri = new javax.swing.JButton();
        lblClved1 = new javax.swing.JLabel();
        lblClved2 = new javax.swing.JLabel();
        lblClved3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFondo.setBackground(new java.awt.Color(255, 255, 255));

        lblDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/kisspng-computer-icons-physician-surgeon-surgeon-5adb4388dca373.8497728715243191129037.png"))); // NOI18N

        lblRinion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Riñon (2).png"))); // NOI18N

        lblClved.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lblClved.setText("CLVED");

        btnDescubiri.setBackground(new java.awt.Color(204, 255, 255));
        btnDescubiri.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        btnDescubiri.setText("DESCUBRIR");
        btnDescubiri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescubiriActionPerformed(evt);
            }
        });

        lblClved1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lblClved1.setText("donante vivo entre familiares"); // NOI18N

        lblClved2.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lblClved2.setText("Un sistema para "); // NOI18N

        lblClved3.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        lblClved3.setText("seleccionar el mejor"); // NOI18N

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondoLayout.createSequentialGroup()
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblClved3)
                            .addComponent(lblClved1)
                            .addComponent(lblClved2)
                            .addGroup(pnlFondoLayout.createSequentialGroup()
                                .addComponent(lblRinion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblClved, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnDescubiri, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblDoctor))
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFondoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblRinion))
                            .addGroup(pnlFondoLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(lblClved)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(lblClved2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblClved3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblClved1)
                        .addGap(104, 104, 104)
                        .addComponent(btnDescubiri, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDescubiriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescubiriActionPerformed
        // TODO add your handling code here:
        GUI_Receptor receptor = new GUI_Receptor();
        receptor.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDescubiriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDescubiri;
    private javax.swing.JLabel lblClved;
    private javax.swing.JLabel lblClved1;
    private javax.swing.JLabel lblClved2;
    private javax.swing.JLabel lblClved3;
    private javax.swing.JLabel lblDoctor;
    private javax.swing.JLabel lblRinion;
    private javax.swing.JPanel pnlFondo;
    // End of variables declaration//GEN-END:variables
}
